# Generated by Django 5.2.15 on 2026-07-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuisier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='budget',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='devis',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='devis',
            name='delai',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='devis',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='photo_plan',
            field=models.FileField(blank=True, null=True, upload_to='devis_fichiers/'),
        ),
        migrations.AddField(
            model_name='devis',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='devis',
            name='type_client',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='devis',
            name='type_produit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='devis',
            name='type_travaux',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='devis',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
