# Generated by Django 5.2.15 on 2026-07-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuisier', '0002_alter_client_prospect_nom_and_more'),
        ('menuisier', '0002_devis_budget_devis_code_postal_devis_delai_and_more'),
    ]

    operations = [
    ]
