# Generated by Django 6.0.5 on 2026-05-20 16:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone_whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client / Prospect',
                'verbose_name_plural': 'Clients / Prospects',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type_travaux', models.CharField(max_length=100)),
                ('materiau_utilise', models.CharField(blank=True, max_length=100)),
                ('budget_indicatif', models.PositiveIntegerField(blank=True, null=True)),
                ('localisation', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('est_termine', models.BooleanField(default=False)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers', to='menuisier.client_prospect')),
            ],
            options={
                'verbose_name': 'Chantier',
                'verbose_name_plural': 'Chantiers',
                'ordering': ['-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_meuble', models.CharField(max_length=150)),
                ('dimensions_approximatives', models.CharField(blank=True, max_length=200)),
                ('materiau', models.CharField(blank=True, max_length=100)),
                ('message_whatsapp_genere', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('relance_j3', 'Relancé à J+3'), ('relance_j7', 'Relancé à J+7'), ('converti', 'Converti en chantier'), ('abandonne', 'Abandonné')], default='en_attente', max_length=20)),
                ('date_relance_j3', models.DateTimeField(blank=True, null=True)),
                ('date_relance_j7', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='menuisier.client_prospect')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ImageChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_image', models.ImageField(upload_to='chantiers/')),
                ('categorie', models.CharField(choices=[('avant', 'Avant'), ('pendant', 'Pendant'), ('apres', 'Après')], default='avant', max_length=10)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menuisier.chantier')),
            ],
            options={
                'verbose_name': 'Image de chantier',
                'verbose_name_plural': 'Images de chantier',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('note', models.PositiveSmallIntegerField(default=5)),
                ('est_valide', models.BooleanField(default=False)),
                ('token_validation', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('chantier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temoignage', to='menuisier.chantier')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temoignages', to='menuisier.client_prospect')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
